name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:   
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Start Azurite (Azure Blob Storage emulator)
        run: docker run --name azurite -d -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:      
          dotnet-version: 2.2.108

      - name: Restore packages
        run: dotnet restore

      - name: Build solution 
        run: dotnet build

      - name: Test solution
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

